### ISSUE TITLE
Block height in restoring wallet doesn't affect a scanning blockchain

### ISSUE THREAD

**Issue by samosudov** [adityapk00/zecwallet-lite#27]
**Describe the bug**
Set height doesn't affect starting height

**To Reproduce**
1. On start, choose "restore from seed"
2. Paste seed phrase and set block height 649171 and click Ok
3. Syncing dialog shows "Syncing from 630000 to _current block_"

**Expected behavior**
Syncing starts from the set height

**Desktop (please complete the following information):**
 - OS:  MacOS 10.14.3 (18D109)
 - Zecwallet Lite v1.0.2

**Comment by adityapk00** [comment]
Thanks for reporting this issue! 

Unfortunately, this is expected behaviour for now. The issue is because of the way the LightClient protocol works, the sync can start only from a "known good" checkpoint. Zecwallet Lite picks the closes checkpoint from the height that you specify, and syncs from there.
