### ISSUE TITLE
Can't choose "From" when sending

### ISSUE THREAD

**Issue by amiller** [adityapk00/zecwallet-lite#35]
I noticed this commit removed the "From" field from the "Send" tab.
fd9d668a4428d2bc71a2db79de9ee43273e0d1b7
This is too bad, since I was relying on selecting the "From" field in order to send a memo from a given t-address.  https://forum.zcashcommunity.com/t/staked-poll-on-zcash-dev-fund-debate/34846/7
I wonder if there's a way to support this workflow optionally?

**Comment by adityapk00** [comment]
Zecwallet Lite doesn't support the 'from' field, in order to make things simpler. Selecting a 'from' will add additional complexity, like making sure there are enough funds to send the amount in the 'from' address, and require tracking individual addresses's confirmed funds (instead of using a single, global confirmed funds). 

 I don't plan on supporting the 'from' field in Zecwallet-Lite. 

In the Zecwallet Fullnode, you can, of course, select the from field as you would normally.
