### ISSUE TITLE
Towards more robust lite wallet privacy (Thoughts and Discussion)

### ISSUE THREAD

**Issue by s-rah** [adityapk00/zecwallet-lite#43]
Today I finally got around to looking at the actual lite wallet protocol implementation, and there are few high level concerns that I think need to be addressed - but they are going to require more consideration, and discussion before any implementation should be attempted.

The primary problem is that, practically, **the anonymity set for transactions is too small**. Some zcash blocks contain a handful of transactions, some only 1 or 2. Given prior research which has shown linking of shielded transactions based on use, it seems clear that the current strategy of per-client random transactions fetches isn't robust.

It needs to be modelled, but I think moving towards a mechanism where all lite wallet clients download all transactions in small blocks, regardless of interest, should go some way to mitigating this - I'd recommend looping in more zcash people to double check.

The above is based on a couple of hours of experiments, and needs more analysis before being taken as a recommended approach.

The original spec also assumed that the networking medium was protected, and so switching the lite wallet to use a tor onion service instead of clearnet so that IP addresses of lite wallet clients are obscured (making linking harder)  - this is something Open Privacy has been building tooling and experience around for a while now, and I have a few other ideas regarding how to better protect both the service and the clients in a more robust manner that might be worth discussing separately.

If this isn't the best forum for more thoughtful technical discussion then I'm happy to move it to somewhere else.

**Comment by adityapk00** [comment]
Can you please post this on the Zcash forums, where the Zcash developer and other wallet developers also hang out? We can continue the discussion there. 

Some notes:
- Technically, lightwallet protocol spec itself actually doesn't leak which blocks contain the user's transactions, because the clients don't need to fetch the transactions in each block. The Compact transactions contain enough info to get the address and amount, but not the memo. 

The reason Zecwallet Lite downloads the full block (and thus leaking the blocks containing the transactions) is to get the incoming memos. 

There is a tradeoff with size here. The more "random" blocks or transactions that are downloaded, the more bandwidth consumed by the client. The lightclient protocol doesn't make a recommendation here, so  Zecwallet Lite trades it off by downloading the full block. (Hence the disclaimer that Zecwallet Lite leaks which blocks contain your Txns to lightwalletd)

- Another issue is transparent transactions, which need to be fetched outside the strict lightclient protocol, which leak transparent txns belonging to the user. 

- The lightclient protocol also contains an issue where it misses the mempool. i.e., the lightclient doesn't have access to the mempool which results in the awkward tracking of send transactions and verified funds. 

Anyway, there's been some discussion already about fixing the anonymity set problem you identified, along with the mempool issue and the memo retrival on the Zcash forms.

**Comment by adityapk00** [comment]
Here's a previous thread from Nathan summarizing the current state of the protocol. 

https://twitter.com/least_nathan/status/1194344366019530753

**Comment by s-rah** [comment]
Done: https://forum.zcashcommunity.com/t/practical-privacy-issues-in-lite-clients/36132

I've tweaked it there to be a bit more generic - but I'll note there are a few things specific to this project in my post above.

**Comment by matthewdgreen** [comment]
I want to bump this. Has there been any thought given to Sarah's proposal? Or alternatively: is there a way I can move to the "download everything using compact blocks, but don't fetch the memos" using a Settings option? Because practically this seems to be a huge information leak.

**Comment by adityapk00** [comment]
Yes, we discussed some of the issues in our last wallet team meeting. I'm working on some of it here in this branch: https://github.com/adityapk00/zecwallet-light-cli/tree/threadpoolsync

Of course, you're welcome to make a PR directly on the main branch as well. 

Closing this issue, so we can discuss it directly on the thread on the community forum.
