### ISSUE TITLE
ZecWallet 1.1.2 won't load

### ISSUE THREAD

**Issue by elraraman** [adityapk00/zecwallet-lite#46]
**Describe the bug**
I downloaded the newest version of the ZecWallet because ZecWallet v1.0.5 was giving me a "No Connection" error. When I try to open ZecWallet 1.1.2, it does not load (i.e. give me a login screen or screen to view my wallet). 

*Expected behavior**
I expected to click "ZecWallet-lite from my launchpad and get a screen similar to ZecWallet v1.0.5, but that did not happen. No screen loads. 

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: MacOs High Sierra 10.13.6 update

**Comment by adityapk00** [comment]
Unfortunatley, this seems like an issue with MacOS High Sierra. Since Catalina, MacOS has required a new type of signing and packaging that looks like it is incompatible. 

Also, I don't have access to a High Sierra machine, so I'm going to close this as wont fix. If you upgrade to Catalina or higher, it should work.

**Comment by elraraman** [comment]
Commenting to let you know your suggestion to upgrade to Catalina worked. Thanks so much!
